<?php

namespace Database\Seeders;

use App\Enums\CategoriaVeiculo;
use App\Enums\CombustivelVeiculo;
use App\Enums\EspecieVeiculo;
use App\Enums\TipoVeiculo;
use App\Models\Vehicle;
use Illuminate\Database\Seeder;

class VehicleSeeder extends Seeder
{
    public function run(): void
    {
        $vehicles = [
            [
                'name'              => 'Caminhão Baú 01 - Distribuição SP',
                'plate'             => 'ABC-1A23',
                'renavam'           => '12345678901',
                'chassis'           => '9BWZZZ377VT004251',
                'vehicle_type'      => TipoVeiculo::Caminhao,
                'category'          => CategoriaVeiculo::Frota,
                'species'           => EspecieVeiculo::Carga,
                'manufacturing_year'=> 2020,
                'model_year'        => 2021,
                'year'              => 2021,
                'brand'             => 'Mercedes-Benz',
                'model'             => 'Atego 1719',
                'color'             => 'Branco',
                'fuel_type'         => CombustivelVeiculo::Diesel,
                'power_hp'          => 190,
                'displacement_cc'   => 6374,
                'doors'             => 2,
                'passenger_capacity'=> 2,
                'transmission_type' => 'Manual',
                'traction_type'     => '4x2',
                'gross_weight'      => 16000,
                'net_weight'        => 6200,
                'cargo_capacity'    => 9800,
                'department'        => 'Logística',
                'responsible_driver'=> 'Marcos Vinicius Pereira',
                'cost_center'       => 'CC-LOG-001',
                'current_location'  => 'Garagem Central - Rio de Janeiro/RJ',
                'is_active'         => true,
                'acquisition_date'  => '2021-03-15',
                'acquisition_value' => 185000.00,
                'observations'      => 'Veículo principal de distribuição da rota SP.',
            ],
            [
                'name'              => 'Caminhão Baú 02 - Distribuição RJ',
                'plate'             => 'DEF-2B34',
                'renavam'           => '23456789012',
                'chassis'           => '9BWZZZ377VT004252',
                'vehicle_type'      => TipoVeiculo::Caminhao,
                'category'          => CategoriaVeiculo::Frota,
                'species'           => EspecieVeiculo::Carga,
                'manufacturing_year'=> 2019,
                'model_year'        => 2020,
                'year'              => 2020,
                'brand'             => 'Volvo',
                'model'             => 'FMX 460',
                'color'             => 'Cinza',
                'fuel_type'         => CombustivelVeiculo::Diesel,
                'power_hp'          => 460,
                'displacement_cc'   => 12800,
                'doors'             => 2,
                'passenger_capacity'=> 2,
                'transmission_type' => 'Automático',
                'traction_type'     => '6x4',
                'gross_weight'      => 25000,
                'net_weight'        => 9500,
                'cargo_capacity'    => 15500,
                'department'        => 'Logística',
                'responsible_driver'=> 'Marcos Vinicius Pereira',
                'cost_center'       => 'CC-LOG-002',
                'current_location'  => 'Garagem Central - Rio de Janeiro/RJ',
                'is_active'         => true,
                'acquisition_date'  => '2020-07-20',
                'acquisition_value' => 320000.00,
                'observations'      => 'Rota RJ - MG.',
            ],
            [
                'name'              => 'Van de Entrega 01',
                'plate'             => 'GHI-3C45',
                'renavam'           => '34567890123',
                'chassis'           => '9BD178TS0L3241001',
                'vehicle_type'      => TipoVeiculo::VanFurgao,
                'category'          => CategoriaVeiculo::Frota,
                'species'           => EspecieVeiculo::Misto,
                'manufacturing_year'=> 2022,
                'model_year'        => 2022,
                'year'              => 2022,
                'brand'             => 'Fiat',
                'model'             => 'Ducato Cargo',
                'color'             => 'Branco',
                'fuel_type'         => CombustivelVeiculo::Diesel,
                'power_hp'          => 148,
                'displacement_cc'   => 2287,
                'doors'             => 3,
                'passenger_capacity'=> 3,
                'transmission_type' => 'Manual',
                'traction_type'     => '4x2',
                'gross_weight'      => 3500,
                'net_weight'        => 1900,
                'cargo_capacity'    => 1600,
                'department'        => 'Logística',
                'responsible_driver'=> null,
                'cost_center'       => 'CC-LOG-003',
                'current_location'  => 'Filial - São Paulo/SP',
                'is_active'         => true,
                'acquisition_date'  => '2022-01-10',
                'acquisition_value' => 135000.00,
                'observations'      => 'Entregas locais na região metropolitana.',
            ],
            [
                'name'              => 'Carro de Representação - Diretoria',
                'plate'             => 'JKL-4D56',
                'renavam'           => '45678901234',
                'chassis'           => '9BWZZZ377VT004254',
                'vehicle_type'      => TipoVeiculo::Passeio,
                'category'          => CategoriaVeiculo::Oficial,
                'species'           => EspecieVeiculo::Passageiro,
                'manufacturing_year'=> 2023,
                'model_year'        => 2023,
                'year'              => 2023,
                'brand'             => 'Toyota',
                'model'             => 'Corolla XEi',
                'color'             => 'Prata',
                'fuel_type'         => CombustivelVeiculo::Flex,
                'power_hp'          => 177,
                'displacement_cc'   => 2000,
                'doors'             => 4,
                'passenger_capacity'=> 5,
                'transmission_type' => 'CVT',
                'traction_type'     => '4x2',
                'gross_weight'      => 1755,
                'net_weight'        => 1340,
                'cargo_capacity'    => null,
                'department'        => 'Diretoria',
                'responsible_driver'=> 'Carlos Eduardo Mendes',
                'cost_center'       => 'CC-DIR-001',
                'current_location'  => 'Sede - São Paulo/SP',
                'is_active'         => true,
                'acquisition_date'  => '2023-05-05',
                'acquisition_value' => 148990.00,
                'observations'      => 'Veículo para uso da diretoria e reuniões externas.',
            ],
            [
                'name'              => 'Pickup Comercial - Compras',
                'plate'             => 'MNO-5E67',
                'renavam'           => '56789012345',
                'chassis'           => '9BM255060N0123456',
                'vehicle_type'      => TipoVeiculo::Pickupe,
                'category'          => CategoriaVeiculo::Frota,
                'species'           => EspecieVeiculo::Misto,
                'manufacturing_year'=> 2021,
                'model_year'        => 2022,
                'year'              => 2022,
                'brand'             => 'Chevrolet',
                'model'             => 'S10 LTZ',
                'color'             => 'Preto',
                'fuel_type'         => CombustivelVeiculo::Diesel,
                'power_hp'          => 200,
                'displacement_cc'   => 2800,
                'doors'             => 4,
                'passenger_capacity'=> 5,
                'transmission_type' => 'Automático',
                'traction_type'     => '4x4',
                'gross_weight'      => 2650,
                'net_weight'        => 1900,
                'cargo_capacity'    => 750,
                'department'        => 'Compras',
                'responsible_driver'=> 'Roberto Silva Santos',
                'cost_center'       => 'CC-COM-001',
                'current_location'  => 'Filial - Belo Horizonte/MG',
                'is_active'         => true,
                'acquisition_date'  => '2022-08-18',
                'acquisition_value' => 195000.00,
                'observations'      => 'Utilizada para visitas a fornecedores.',
            ],
            [
                'name'              => 'Utilitário - Manutenção',
                'plate'             => 'PQR-6F78',
                'renavam'           => '67890123456',
                'chassis'           => '9BWZZZ377VT004256',
                'vehicle_type'      => TipoVeiculo::Utilitario,
                'category'          => CategoriaVeiculo::Frota,
                'species'           => EspecieVeiculo::Misto,
                'manufacturing_year'=> 2018,
                'model_year'        => 2019,
                'year'              => 2019,
                'brand'             => 'Volkswagen',
                'model'             => 'Saveiro Robust',
                'color'             => 'Vermelho',
                'fuel_type'         => CombustivelVeiculo::Flex,
                'power_hp'          => 104,
                'displacement_cc'   => 1600,
                'doors'             => 2,
                'passenger_capacity'=> 2,
                'transmission_type' => 'Manual',
                'traction_type'     => '4x2',
                'gross_weight'      => 1530,
                'net_weight'        => 1000,
                'cargo_capacity'    => 530,
                'department'        => 'Manutenção',
                'responsible_driver'=> null,
                'cost_center'       => 'CC-MAN-001',
                'current_location'  => 'Garagem - Curitiba/PR',
                'is_active'         => true,
                'acquisition_date'  => '2019-02-28',
                'acquisition_value' => 62000.00,
                'observations'      => 'Suporte às equipes de manutenção interna.',
            ],
        ];

        $created = 0;
        foreach ($vehicles as $vehicle) {
            Vehicle::firstOrCreate(
                ['plate' => $vehicle['plate']],
                $vehicle
            );
            $created++;
        }

        $this->command->info("✅ {$created} veículos semeados.");
    }
}


